Moon day
emilyPhee/yemayoga.com pull request #23
Opened 2022-10-06 21:45 UTC by emilyPhee

Add Moon Day Component
- installed Lune package 
- calculate Full Moon and New Moon phase
- display with grid

2022-10-06 23:03 UTC, emilyPhee commented
Add Moon Day Component

 - installed Lune package
 - calculate Full Moon and New Moon phase
 - display with grid

2022-10-07 17:31 UTC, emilyPhee commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ashtanga: Moon day](https://trello.com/c/7OEpQayh/24-ashtanga-moon-day)

2022-10-07 21:25 UTC, anthopark requested changes
🚀

2022-10-07 21:25 UTC, anthopark commented on nextjs-client/src/components/YogaClassInfo/MoonDay/index.js
> +  const lune = require('lune');
change this to the import statement

2022-10-07 22:12 UTC, anthopark approved these changes

2022-10-07 22:48 UTC, merged