Yoga classes
emilyPhee/yemayoga.com pull request #7
Opened 2022-09-16 00:14 UTC by emilyPhee

- Add class list component
- Add class component containing image, name, duration and level.
- Display yoga class data from Sanity.

2022-09-16 00:17 UTC, emilyPhee commented
![](https://github.trello.services/images/mini-trello-icon.png) [Home Page: Yoga Classes Section](https://trello.com/c/nMqRnax4/13-home-page-yoga-classes-section)

2022-09-17 21:55 UTC, anthopark requested changes

2022-09-17 21:55 UTC, anthopark commented on nextjs-client/.env
> +SANITY_DATASET=production
make sure to gitignore this file

2022-09-17 22:44 UTC, emilyPhee reviewed
reviewed

2022-09-17 22:52 UTC, anthopark approved these changes
Great job!

2022-09-17 22:55 UTC, merged